### ISSUE TITLE
Your library not avaible in codeignter 3

### ISSUE THREAD

**Issue by sidaurukfreddy** [avenirer/MY_Upload#1]
Hi Avenir thanks for your effort, few days ago i have trouble about it but i change the way and succes but still confused why your library not working in CI 3, every time i load the library give errors that i wrong load your library, please try it !

So here is problem i have table which image, name_product, price_product it can be insert as array (Multiple images and input type)

i can get the name each file which uploaded, but get post name_product and proce_product i cannot !

Sorry not post the errors cause code in the another Computer, Thanks

Freddy

**Comment by avenirer** [comment]
I don't understand the problem you're facing...
